# Generated by Django 4.2 on 2023-04-14 08:11

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('promo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='promopeople',
            name='phone_numbers',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=20, region=None, verbose_name='Номер владельца'),
        ),
        migrations.AlterField(
            model_name='promopeople',
            name='telegram_id',
            field=models.IntegerField(max_length=30, verbose_name='Телеграм-ID докладчика'),
        ),
        migrations.AlterField(
            model_name='question',
            name='telegram_user_id',
            field=models.IntegerField(max_length=30, verbose_name='Телеграм-ID задающего вопрос'),
        ),
    ]
