# Generated by Django 4.2 on 2023-04-14 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promo', '0002_promopeople_phone_numbers_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promopeople',
            name='telegram_id',
            field=models.IntegerField(verbose_name='Телеграм-ID докладчика'),
        ),
        migrations.AlterField(
            model_name='question',
            name='telegram_user_id',
            field=models.IntegerField(verbose_name='Телеграм-ID задающего вопрос'),
        ),
    ]
